select
   formid,
   case when iwon_school_id = '' then null else iwon_school_id::int end as location_id,
   observation_date::date,
   date_trunc('week', observation_date::date)::date as week,
   received_on,
   term_week,
	term_id,
	term_name,
   iwon_country as country,
   admin_3_name,
   iwon_partner_name as partner,
   iwon_school_name as location,
   iwon_staff_name as field_officer,
   date_launched,
   country as commcare_country,
   hq_user as commcare_user,
   username as commcare_username,
   school_name as commcare_school_name,
   partner_organization as commcare_partner_name,
   minutes_used::int,
   started_time,
   time_on_task,
   observe_setup,
   completed_time,
   session_rating::int,
   absent_students::int,
   action_needed_iw,
   first_time_issue,
   identified_issues,
   issue_description,
   other_observation,
   recollection_time,
   action_needed_pimu,
   session_start_time,
   feedback_to_teacher,
   minutes_teacher_away,
   sessions_previous_week,
   no_sessions_previous_week,
   latitude,
	longitude,
	case when gps_accuracy = '' then null else gps_accuracy::float end as gps_accuracy,
   ST_Distance(ST_Point(longitude, latitude)::GEOGRAPHY,ST_Point(school_longitude, school_latitude)::GEOGRAPHY)/1000 as distance_from_school
from {{ref("int_weekly_monitoring_survey")}}
where observe_setup = 'yes' or observe_setup = 'no'
