select 
id, 
uuid, 
start,
"end",
country,
field_officer,
LTRIM(school_name, 's') as location_id , 
observation_date,
setup_observations, 
tablet_use_observations, 
tablet_usage_mins,
closing_observations,
session_rating,
other_session_obs,
distribution,
distributed_equipment,
headset_delivery as headsets_delivered,
cable_delivery as cables_delivered,
protector_delivery as protectors_delivered,
decommission_tablet as decommission_tablets,
other_decommission as other_decommission, 
decommissioned_headsets as headsets_decommissioned,
decommissioned_cables as cables_decommissioned,
decommisioned_protectors as protectors_decommissioned,
replacements,
tablet_replacements as tablets_to_replace,
headset_replacements as headsets_to_replace, 
cable_replacements as cables_to_replace, 
protector_replacements as protectors_to_replace,
other_replacement_obs,
instance_id, 
modified_at,
submitted_at,
submission_submitted_by
from {{source('ona_data','monitoring_crs_pilot')}}